### ISSUE TITLE
Bitcode related error.

### ISSUE THREAD

**Issue by dzaga71** [VoIPGRID/Vialer-pjsip-iOS#16]
Hello!

I'm using library as framework instead of Pod because the include files conflict with Realm. But I can't get binary for real device (works fine with Simulator). I'm getting this error

...Libs/VialerPJSIP.framework/VialerPJSIP(darwin_dev.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '...Libs/VialerPJSIP.framework/VialerPJSIP' for architecture armv7

Any help will be appreciated.

**Comment by rcorrie** [comment]
Seeing this as well. I have to disable bitcode altogether to build run on a real device.

**Comment by redmerloen** [comment]
Version 3.3.0 of this library has been released with bitcode enabled. Please see if this fixes your issue
