### ISSUE TITLE
Cannot make call on device (simulator ok)

### ISSUE THREAD

**Issue by rcorrie** [VoIPGRID/Vialer-pjsip-iOS#21]
### Version

3.1.0

### Expected behaviour

`pjsua_call_make_call` should properly open sound device and place the call

### Actual behaviour

`pjsua_call_make_call` fails with `Unable to open sound device: Unknown error 506637 [status=506637]` and the call is not made

### Stacktrace / Error message

`Unable to open sound device: Unknown error 506637 [status=506637]`

### Other info

This only happens when running on a real device. When testing in the simulator, everything works perfectly.

Before failing, PJSIP tries to open the sound device on various clock rates, and each one fails with `AUIOClient_StartIO failed (-66637)`.

**Comment by rcorrie** [comment]
Please close, this was an issue with another library that wrapped this one.

**Comment by fukemy** [comment]
hi, can u provide any example? thanks
