### ISSUE TITLE
VialerPJSIP/inttypes.h not found

### ISSUE THREAD

**Issue by softwaremissinglink** [VoIPGRID/Vialer-pjsip-iOS#3]
The pj/compact/cc_gcc.h file included in the Pod has "#include <VialerPJSIP/inttypes.h>" which doesn't exists so Xcode fails to compile. Changing it to just <inttypes.h> works. BTW the cc_gcc.h in the Pods folders is ok but the one used under Framework/A/Headers is not.

**Comment by spindleredmer** [comment]
With the next release of this Vialer-pjsip-iOS the <inttypes.h> shall not be prefixed with VialerPJSIP anymore
