### ISSUE TITLE
WEBRTC calling to Only PSTN for ios app in swift

### ISSUE THREAD

**Issue by sandeep2244** [VoIPGRID/Vialer-pjsip-iOS#32]
hello,

i am developing app for ios in swift(Webrtc),
i would like to know About how i can use pjsip library for that,
WEBRTC -> PJSIP(SIP) -> PSTN  (In IOS)
How can i do this,any one know about any link  or cocopods for that 

Thank you

**Comment by murugancmi** [comment]
@sandeep2244  if you want to make a call to PSTN from your app you need to use PJSIP or SIP.JS(SIP over websocket and media goes through WebRTC), I think you need to understand basic different between WebRTC and SIP https://www.voxbone.com/blog/webrtc-future-without-sip.
