### ISSUE TITLE
BCG729 Integration

### ISSUE THREAD

**Issue by ForGuru** [VoIPGRID/Vialer-pjsip-iOS#34]
### Version

2.8

### File / Feature

g729/ bcg729 Codecs Integration 

### Expected behaviour

g729/ bcg729 Codecs Integration 

### Actual behaviour

Trying to figure out how to integrate bcg729. 

### Stacktrace / Error message

NNA

### Other info

{anything else that might be related/useful}

**Comment by jeremynorman89** [comment]
I'd recommend checking out my reply here: https://github.com/VoIPGRID/VialerSIPLib/issues/181#issuecomment-477986545
